apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: xpto/kyma-demo:latest
          resources:
            limits:
              memory: "25Mi"
              cpu: "0.25"
          ports:
            - containerPort: 8080
