apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api
spec:
  selector:
    matchLabels:
      app: public-api
  replicas: 2
  template:
    metadata:
      labels:
        app: public-api
    spec:
      containers:
        - name: public-api
          image: wagnermanganelli164/k8s-demo-public-api:latest
          resources:
            limits:
              memory: "25Mi"
              cpu: "0.25"
          ports:
            - containerPort: 8080
          # envFrom:
          #   - configMapRef:
          #       name: public-api-configmap
