apiVersion: v1
kind: Service
metadata:
  name: public-api-service
spec:
  selector:
    app: public-api
  type: ClusterIP
  ports:
    - name: public-api-service
      port: 80
      targetPort: 8080
      protocol: TCP
