apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-api
spec:
  selector:
    matchLabels:
      app: private-api
  replicas: 1
  template:
    metadata:
      labels:
        app: private-api
    spec:
      containers:
        - name: private-api
          image: xpto/k8s-demo-private-api:latest
          resources:
            requests:
              memory: "20Mi"
              cpu: "0.1"
            limits:
              memory: "25Mi"
              cpu: "0.15"
          ports:
            - containerPort: 8080
          # envFrom:
          #   - configMapRef:
          #       name: goserver-configmap
